name = 'BlackDark-Developer-Theme'
license = 'MIT'
licenselink = 'https://github.com/BlackDark/hugo-theme-developer/LICENSE'
description = 'Developer theme based on https://github.com/xriley/Developer-Theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/BlackDark/hugo-theme-developer'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'BlackDark'
  homepage = 'https://github.com/BlackDark'

# If porting an existing theme
[original]
  author = 'xriley'
  homepage = 'https://github.com/xriley/Developer-Theme'
  repo = 'https://github.com/xriley/Developer-Theme'
